# Generated by Django 6.0.2 on 2026-04-13 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('nucleo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.empleado'),
        ),
        migrations.AddField(
            model_name='incidenciadia',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.empleado'),
        ),
        migrations.AddField(
            model_name='incidenciadia',
            name='incidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='core.incidencia'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_core', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turno',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.turno'),
        ),
        migrations.AlterUniqueTogether(
            name='empresausuario',
            unique_together={('usuario', 'empresa')},
        ),
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together={('empresa', 'nombre')},
        ),
    ]
