# Generated by Django 6.0.2 on 2026-04-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='incidenciadia',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
    ]
