# Generated by Django 5.0.6 on 2026-06-30 21:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_incidencia_tipo_alter_incidenciadia_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='empresa',
            name='rfc',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
