# Generated by Django 5.0.6 on 2026-06-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_empresa_fecha_alta_empresa_razon_social_empresa_rfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Empresa activa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre comercial'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200, verbose_name='Razón social'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='rfc',
            field=models.CharField(blank=True, max_length=20, verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='subdominio',
            field=models.CharField(max_length=50, unique=True, verbose_name='Subdominio'),
        ),
    ]
