# Generated by Django 5.0.6 on 2026-07-02 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_empresa_activa_alter_empresa_fecha_alta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresausuario',
            options={'verbose_name': 'Usuario-Empresa', 'verbose_name_plural': 'Usuarios-Empresa'},
        ),
    ]
