# Generated by Django 5.0.6 on 2026-07-02 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_perfil_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ('empresa__nombre', 'nombre'), 'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
    ]
