# Generated by Django 6.0.2 on 2026-04-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='costo_hora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
