# Generated by Django 5.0.6 on 2026-07-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_empleado_costo_hora'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ('nombre',), 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AddField(
            model_name='departamento',
            name='trabaja_fines_semana',
            field=models.BooleanField(default=False, verbose_name='Trabaja fines de semana'),
        ),
    ]
