# Generated by Django 6.0.2 on 2026-03-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_departamento_empleado_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
