# Generated by Django 5.0.6 on 2026-07-02 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together=set(),
        ),
    ]
