# Generated by Django 6.0.2 on 2026-03-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_departamento_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='control_horario',
            field=models.BooleanField(default=True, verbose_name='Control de horario'),
        ),
    ]
