# Generated by Django 6.0.2 on 2026-03-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nucleo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="control_horario",
            field=models.BooleanField(default=True),
        ),
    ]
