# Generated by Django 5.0.6 on 2026-07-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_alter_empleado_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso'),
        ),
    ]
