# Generated by Django 6.0.2 on 2026-03-07 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_empleado_control_horario'),
        ('nucleo', '0005_add_control_horario'),
    ]

    operations = [
    ]
