# Generated by Django 6.0.2 on 2026-03-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0006_merge_20260306_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='dias_trabajo',
            field=models.CharField(default='0,1,2,3,4', max_length=20),
        ),
    ]
