# Generated by Django 6.0.2 on 2026-03-24 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_incidenciadia_unique_together_turno_and_more'),
        ('nucleo', '0007_empleado_dias_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.turno'),
        ),
    ]
