# Generated by Django 6.0.2 on 2026-02-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('tipo_dia', models.CharField(choices=[('NORMAL', 'Normal'), ('PERMISO', 'Permiso'), ('VACACIONES', 'Vacaciones'), ('INCAPACIDAD', 'Incapacidad')], default='NORMAL', max_length=20)),
            ],
        ),
    ]
