# Generated by Django 6.0.2 on 2026-02-26 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.empleado'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('empresa', 'empleado', 'fecha')},
        ),
    ]
