# Generated by Django 6.0.2 on 2026-04-13 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asistencia', '0001_initial'),
        ('core', '0001_initial'),
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.empleado'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='asistencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='asistencia.asistencia'),
        ),
        migrations.AddField(
            model_name='tiempoextra',
            name='asistencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.asistencia'),
        ),
        migrations.AddField(
            model_name='tiempoextra',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.empleado'),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('empresa', 'empleado', 'fecha')},
        ),
    ]
