# Generated by Django 6.0.2 on 2026-02-28 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SALIDA_PERMISO', 'Salida con permiso'), ('REGRESO', 'Regreso')], max_length=20)),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='asistencia.asistencia')),
            ],
        ),
    ]
