# Generated by Django 5.0.6 on 2026-07-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('SALIDA_PERMISO', 'Salida con permiso'), ('REGRESO', 'Regreso'), ('INICIO_TIEMPO_EXTRA', 'Inicio tiempo extra'), ('FIN_TIEMPO_EXTRA', 'Fin tiempo extra')], max_length=20),
        ),
    ]
