# Generated by Django 6.0.2 on 2026-03-01 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_movimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimiento',
            old_name='hora',
            new_name='fecha_hora',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='observacion',
        ),
    ]
