# Generated by Django 6.0.2 on 2026-03-02 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_rename_hora_movimiento_fecha_hora_and_more'),
        ('core', '0002_initial'),
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiempoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('POST_JORNADA', 'Post Jornada'), ('DIA_DESCANSO', 'Día de Descanso')], max_length=20)),
                ('asistencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tiempos_extra', to='asistencia.asistencia')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
    ]
