# Generated by Django 6.0.2 on 2026-03-12 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_tiempoextra'),
        ('core', '0002_initial'),
        ('nucleo', '0007_empleado_dias_trabajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('PERMISO', 'Salida con permiso'), ('REGRESO', 'Regreso de permiso'), ('TIEMPO_EXTRA', 'Inicio tiempo extra')], max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
