# Generated by Django 6.0.2 on 2026-03-18 20:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0006_movimientoasistencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='fecha_hora',
        ),
        migrations.RemoveField(
            model_name='tiempoextra',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='tiempoextra',
            name='tipo',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='fecha',
            field=models.DateField(default=datetime.date(2026, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimiento',
            name='hora',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiempoextra',
            name='horas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiempoextra',
            name='asistencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.asistencia'),
        ),
        migrations.AlterField(
            model_name='tiempoextra',
            name='hora_fin',
            field=models.TimeField(),
        ),
    ]
