# Generated by Django 6.0.2 on 2026-03-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0007_remove_movimiento_fecha_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiempoextra',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
