# Generated by Django 6.0.2 on 2026-03-20 22:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0008_alter_tiempoextra_hora_fin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ['fecha', 'hora']},
        ),
        migrations.AddField(
            model_name='movimiento',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=20),
        ),
        migrations.DeleteModel(
            name='MovimientoAsistencia',
        ),
    ]
