# Generated by Django 6.0.2 on 2026-03-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0009_alter_movimiento_options_movimiento_creado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('SALIDA_PERMISO', 'Salida con permiso'), ('REGRESO', 'Regreso')], max_length=20),
        ),
    ]
